In [2]:
!pip install numpy
!pip install pandas
import numpy as np



In [11]:
arr1 = np.array([1,2,"w"])
arr2 = np.array([[1,2,3],
                 ["a","b","c"]])

arr3 = np.array([[[1,2,3],["a","b","c"]],
                 [[9,8,7],["z","y","w"]],
                 [[4,5,6],["t","s","r"]]])

print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print()
print(arr2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
print()
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)

['1' '2' 'w']
(3,)
<U21
1

[['1' '2' '3']
 ['a' 'b' 'c']]
(2, 3)
<U21
2

[[['1' '2' '3']
  ['a' 'b' 'c']]

 [['9' '8' '7']
  ['z' 'y' 'w']]

 [['4' '5' '6']
  ['t' 's' 'r']]]
(3, 2, 3)
<U21
3


In [14]:
arr = np.array(["1","2","3","4","5"])
print(arr.dtype)

float_arr = arr.astype("float")
print(float_arr.dtype)

int_arr = arr.astype("int")
print(int_arr.dtype)

<U1
float64
int64


In [15]:
arr = np.arange(10)

#slicing
arr[0:6]

#indexing
arr[-1]

print(arr > 5)
print(arr[arr>5])


[False False False False False False  True  True  True  True]
[6 7 8 9]


In [19]:
arr_z = np.zeros((3,2),dtype='int32')
print(arr_z)

print()
print(arr_z, arr_z.ndim, arr_z.dtype, arr_z.shape)

[[0 0]
 [0 0]
 [0 0]]

[[0 0]
 [0 0]
 [0 0]] 2 int32 (3, 2)


In [26]:
arr_ones = np.ones((10,10),dtype="int")
print(arr_ones)
arr_ones

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### reshape() - 차원과 크기 변경

In [29]:
arr_1 = np.arange(10)
print(arr_1)

print()

arr_rshped = arr_1.reshape(2,5)
print(arr_rshped)

print()

arr_rshped_2 = arr1.reshape(5,2)
print(arr_rshped_2)

print()

arr_rshped_3 = arr1.reshape(3,4) #error size mismatch
print(arr_rshped_3)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]



ValueError: cannot reshape array of size 3 into shape (5,2)

In [30]:
arr_1 = np.arange(8)
print(arr_1)

print()

arr_2 = arr.reshape(-1,4)
print(arr_2)

[0 1 2 3 4 5 6 7]



ValueError: cannot reshape array of size 10 into shape (4)

In [31]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5) # 5열에 맞춰서 -> 행을 만들어줘 (알아서)
print(array2)
print(array2.shape)

array3 = array1.reshape(5, -1) # 5행에 맞춰서 -> 열을 만들어줘 (알아서)
print(array3)
print(array3.shape)

array4 = array1.reshape(2, -1) # 2행에 맞춰서 -> 열을 만들어줘 (알아서)
array4

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 인덱싱, 슬라이싱

In [32]:
arr = np.arange(1,10)
print(arr[0])
print(arr[0:5])
print(arr[:])


1
[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]


In [41]:
arr = np.arange(1,10)
arr2 = arr.reshape(3,3)
print(arr2)

print(arr2[1,1])
print(arr2[2,2])
print(arr2[0,])
print(arr2[0,0:3])

print(arr2[1,])
print(arr2[1,:])
print(arr2[1,0:3])

print(arr2[:,2])
print(arr2[0:3,2])

arr3 = arr2[2,:1]
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[3 6 9]
[3 6 9]
[7]


In [42]:
arr = np.arange(1,10)
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

## sort() 정렬

In [51]:
arr = np.array([10, 30, 5, 1, 100])
arr_sorted = np.sort(arr)
print(arr_sorted)


arr_desc = arr_sorted[::-1]
print(arr_desc)

# np.sort(arr), Reverse == True

[  1   5  10  30 100]
[100  30  10   5   1]


In [53]:
arr_countries = np.array(["kor", "usa", "canada"])
arr_sorted = np.sort(arr_countries)
print(arr_sorted)

['canada' 'kor' 'usa']


## 행렬의 연산

In [62]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

print(arr1)
print("  +, x")
print(arr2)

print()

add_arr = np.add(arr1,arr2)
print(add_arr)

print()

mult_arr = np.multiply(arr1,arr2)
print(mult_arr)

print()

arr_dot = np.dot(arr1,arr2)
print(arr_dot)

[[1 2]
 [3 4]]
  +, x
[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]

[[ 5 12]
 [21 32]]

[[19 22]
 [43 50]]


In [80]:
#Q1. 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요.

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

avg_arr_0 = np.mean(arr, axis = 1)
print(avg_arr_0)

[2. 5. 8.]


In [94]:
# Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요.

arr = np.array([1, 2, 3, 4, 5, 6])
arr_evens = arr[::2]
print(arr_evens)

arr_evens_kim = np.arange(0,arr.size,2)
print(arr_evens_kim)

print(arr[arr_evens_kim])

#arr_diag = arr[0, 0], arr[1, 1], arr[2,2] ??

[1 3 5]
[0 2 4]
[1 3 5]


In [99]:
# Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요.

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])



arr_diag = arr[0, 0], arr[1, 1], arr[2,2]
print(arr_diag)
print(np.diag(arr))
print(arr.diagonal(0))

(1, 5, 9)
[1 5 9]
[1 5 9]


In [101]:
#Q4. 2차원 배열의 표준편차를 구하시오

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


# Pandas

In [10]:
import numpy as np
import pandas as pd

In [104]:
pd.__version__

'1.5.3'

## Series
- 한개의 컬럼으로 구성된 1차원 데이터 셋

In [129]:
data = ["A", "B", "C", "D", "E"]
se = pd.Series(data)
print(se)

0    A
1    B
2    C
3    D
4    E
dtype: object


In [130]:
print(se.index)
print(se.values)
print()
print(se[0])
print(se[0:3])

RangeIndex(start=0, stop=5, step=1)
['A' 'B' 'C' 'D' 'E']

A
0    A
1    B
2    C
dtype: object


In [131]:
se.index.name = "No. "
print(se)
print()
se.name = "alphabet"
print(se)

No. 
0    A
1    B
2    C
3    D
4    E
dtype: object

No. 
0    A
1    B
2    C
3    D
4    E
Name: alphabet, dtype: object


In [132]:
se.index = ["a","b","c","d","e"]
print(se)

a    A
b    B
c    C
d    D
e    E
Name: alphabet, dtype: object


## Data Frame
- 기획직군, PM직군도 Data Analysis 기술 장착하는 추세 (default)

In [1]:
import numpy as np
import pandas as pd

In [20]:
data_A = np.array([[1,2,3], [4,5,6], [7,8,9]])
columms_A = ['D','E','F']

In [17]:
print(pd.DataFrame(data_A))
print()
print(pd.DataFrame(data=data_A))

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [22]:
print(pd.DataFrame(data=data_A, index = ["A","B","C"]))
print(pd.DataFrame(data=data_A, index = ["A","B","C"], columns=columms_A))

   0  1  2
A  1  2  3
B  4  5  6
C  7  8  9
   D  E  F
A  1  2  3
B  4  5  6
C  7  8  9


In [23]:
data_B = {
    'country': ["kor", "usa", "china", "japan"],
    'rank': [1, 2, 3, 4],
    'grade': ['A', 'B', 'C', 'D']
}
df = pd.DataFrame(data_B)
print(df)

  country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D


In [25]:
# index 값 변경
df.index = ["a", "b", "c", "d"]
print(df)

  country  rank grade
a     kor     1     A
b     usa     2     B
c   china     3     C
d   japan     4     D


In [26]:
# 기존 입력된 값을 인덱스로 추가
new_df = df.set_index("rank")
print(new_df)

     country grade
rank              
1        kor     A
2        usa     B
3      china     C
4      japan     D


In [28]:
# 기존 입력된 값을 인덱스로 추가 (2개)
new_df = df.set_index(["rank","grade"])
print(new_df)

           country
rank grade        
1    A         kor
2    B         usa
3    C       china
4    D       japan


## Data Selection
 - df.컬럼명, df[컬럼명]
 - df.loc[] # 인덱스 명, 컬럼명 기반이라 좀 더 직관적이다. df.loc[0:100, ["rank", "grade"]]
 - df.iloc[] # 위치기반이라 숫자데이터가 들어간다. df.iloc[:,0:3]

In [42]:
# (1) df.컬럼명, df['컬럼명']
print(df.country)

a      kor
b      usa
c    china
d    japan
Name: country, dtype: object


In [33]:
print(df['country'])

a      kor
b      usa
c    china
d    japan
Name: country, dtype: object


In [35]:
# Data Frame안에 한개만 있을땐 대괄호가 하나만 있어도 되지만, 두개 이상일 경우 리스트로 만들어야 하기때문에 대괄호로 한번 더 감싸 줘야함
print(df['rank','country'])

KeyError: ('rank', 'country')

In [37]:
print(df[['rank','country']])
print()
print(df[['rank', 'grade','country']])
print()
columns = ['rank', 'country']
print(df[columns])

   rank country
a     1     kor
b     2     usa
c     3   china
d     4   japan

   rank grade country
a     1     A     kor
b     2     B     usa
c     3     C   china
d     4     D   japan

   rank country
a     1     kor
b     2     usa
c     3   china
d     4   japan


In [40]:
test_column1 = ['rank', 'country']
test_column2 = ['rank', 'grade']
test_column3 = ['grade', 'country']

new_df1 = df[test_column1]
new_df2 = df[test_column2]
new_df3 = df[test_column3]

print(new_df1)
print()
print(new_df2)
print()
print(new_df3)


   rank country
a     1     kor
b     2     usa
c     3   china
d     4   japan

   rank grade
a     1     A
b     2     B
c     3     C
d     4     D

  grade country
a     A     kor
b     B     usa
c     C   china
d     D   japan


In [48]:
# (2) loc[인덱스명, 컬럼명]
print(df)
print()

print(df.loc["a"])
print()
print(df.loc["a", "grade"])
print()
print(df.loc["c", ["grade","rank"]])
print()
print(df.loc["a":"c", ["grade","rank"]])
print()
print(df.loc["a":, ["grade","rank"]])

  country  rank grade
a     kor     1     A
b     usa     2     B
c   china     3     C
d   japan     4     D

country    kor
rank         1
grade        A
Name: a, dtype: object

A

grade    C
rank     3
Name: c, dtype: object

  grade  rank
a     A     1
b     B     2
c     C     3

  grade  rank
a     A     1
b     B     2
c     C     3
d     D     4


In [52]:
print(df.loc[:])
# print(df.loc[[],[:]]) -> loc를 받을때 행이 생략되고 컬럼이 들어올 수 있지만, 이렇게 하면 컬럼이 지정이 안되기 때문에 실행이 안됨

  country  rank grade
a     kor     1     A
b     usa     2     B
c   china     3     C
d   japan     4     D


In [90]:
# country 값이 kor, usa 인 값을 출력해 주세요
print(df["country"]=="kor")
print()
print(df[df["country"]=="kor"])
print()
# print(df[df["country"]=="kor" or df["country"]=="usa"])
print(df[(df["country"]=="kor") | (df["country"]=="usa")])

0     True
1    False
2    False
3    False
Name: country, dtype: bool

  country  rank grade
0     kor     1     A



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [61]:
# rank 가 3보다 큰 겂을 찾아주세요

print(df['rank']>2)
print(df[df['rank']>2])

a    False
b    False
c     True
d     True
Name: rank, dtype: bool
  country  rank grade
c   china     3     C
d   japan     4     D


In [79]:
# (3) iloc[인덱스, 컬럼인덱스] => location 위치 기반으로 데이터를 가져온다.
print(df)
print()
# print(df.loc[0]) # -> 에러, loc뒤에는 인덱스"명", 컬럼"명"이 들어와야함
print(df.iloc[0])
print()
print(df.iloc[0:2]) # 범위를 가져올 때도 범위를 챙겨야함
print()
print(df.iloc[:,:]) # iloc 사용할 땐 범위로 가져올 수 있다

  country  rank grade
a     kor     1     A
b     usa     2     B
c   china     3     C
d   japan     4     D

country    kor
rank         1
grade        A
Name: a, dtype: object

  country  rank grade
a     kor     1     A
b     usa     2     B

  country  rank grade
a     kor     1     A
b     usa     2     B
c   china     3     C
d   japan     4     D


In [81]:
new_df = df
new_df.index = [0, 1, 2, 3]
print(new_df)

  country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D


In [85]:
print(new_df.loc[0])
print()
print(new_df.loc[0:3]) # 인덱스명 -> 숫자
print()
print(new_df.iloc[0:3]) # 인덱스

country    kor
rank         1
grade        A
Name: 0, dtype: object

  country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D

  country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C


## filter()를 통한 데이터 가져오기

In [96]:
print(df)
print()
print(df.filter(like = "a", axis = 0))
print()
df.filter(like = "0", axis = 0)

  country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D

Empty DataFrame
Columns: [country, rank, grade]
Index: []



country  rank grade
0     kor     1     A

In [99]:
df.filter(like = 'a', axis = 1) # 컬럼 값 중에서 a가 포함된 컬럼 찾아주세요

rank grade
0     1     A
1     2     B
2     3     C
3     4     D

In [100]:
df.filter(like = 'c', axis = 1) # 컬럼 값 중 c가 포함된 컬럼 찾아주세요

country
0     kor
1     usa
2   china
3   japan

In [104]:
president = pd.Series(["yoon","biden","jinping","kishida"])
print(president)
print()

df["president"] = president
print(df)
# 기존에 있는 컬럼의 값들을 계산해서 => 또 다른 컬럼을 추가하는 것.

0       yoon
1      biden
2    jinping
3    kishida
dtype: object

  country  rank grade president
0     kor     1     A      yoon
1     usa     2     B     biden
2   china     3     C   jinping
3   japan     4     D   kishida


In [118]:
gdp = pd.Series(["1000", "2000", "3000", "4000"])
df["gdp"] = gdp
df["etc"] = 0

print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao   NaN         False    0


In [123]:
print(df['rank'] < 3)
df['boolean_rank'] = df['rank'] < 3

print()

print(df)

0     True
1     True
2    False
3    False
7    False
Name: rank, dtype: bool

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao   NaN         False    0


In [124]:
df.loc[0]

country          kor
rank               1
grade              A
president       yoon
gdp             1000
boolean_rank    True
etc                0
Name: 0, dtype: object

In [125]:
df.loc[7] = ['singapore', 5, 'E', 'jiao', "2000", False, 0]
print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao  2000         False    0


In [127]:
df.iloc[2] = ['Indonesia', 3, 'E', 'dodo', "1500", False, 0]
print(df)

df.iloc[2] = ['China', 3, 'C', 'jinping', "3000", False, 0]
print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2  Indonesia     3     E      dodo  1500         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao  2000         False    0
     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao  2000         False    0


In [131]:
# drop
df.drop(3)
print(df)
print()
df.drop('etc', axis=1)
print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao  2000         False    0

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
3      japan     4     D   kishida  4000         False    0
7  singapore     5     E      jiao  2000         False    0


In [132]:
# inplace옵션
df.drop(3, inplace=True) #정말로 삭제하시겠습니까? True = 네, False = 아니오
print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
7  singapore     5     E      jiao  2000         False    0


In [133]:
print(df)

     country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
7  singapore     5     E      jiao  2000         False    0


In [134]:
new_df = df.drop(3) # 이미 지웠기 때문에 에러가 남

KeyError: '[3] not found in axis'

In [136]:
new_df = df.drop(0)
print(new_df)

new_df = df.drop(3)

     country  rank grade president   gdp  boolean_rank  etc
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
7  singapore     5     E      jiao  2000         False    0


KeyError: '[3] not found in axis'

## 집합함수 (Aggregation)
- df.sum()
- df.mean()
- df.min()
- df. max()
- df. describe()

- df.unique()
- df.nunique()

In [137]:
df.sum()

country         korusaChinasingapore
rank                              11
grade                           ABCE
president       yoonbidenjinpingjiao
gdp                 1000200030002000
boolean_rank                       2
etc                                0
dtype: object

In [158]:
print(df.mean())


rank            2.750000e+00
gdp             2.500500e+14
boolean_rank    5.000000e-01
etc             0.000000e+00
check                    NaN
dtype: float64

rank            2.75
boolean_rank    0.50
etc             0.00
check            NaN
dtype: float64


/var/folders/0t/816d84452dn7h591gjkg32_m0000gn/T/ipykernel_4365/1952998678.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df.mean())


In [159]:
print(df.mean(numeric_only= True))

rank            2.75
boolean_rank    0.50
etc             0.00
check            NaN
dtype: float64


In [139]:
df.max()

country          usa
rank               5
grade              E
president       yoon
gdp             3000
boolean_rank    True
etc                0
dtype: object

In [140]:
df.min()

country         China
rank                1
grade               A
president       biden
gdp              1000
boolean_rank    False
etc                 0
dtype: object

In [141]:
df.describe()

rank  etc
count  4.000000  4.0
mean   2.750000  0.0
std    1.707825  0.0
min    1.000000  0.0
25%    1.750000  0.0
50%    2.500000  0.0
75%    3.500000  0.0
max    5.000000  0.0

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 7
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   country       4 non-null      object
 1   rank          4 non-null      int64 
 2   grade         4 non-null      object
 3   president     4 non-null      object
 4   gdp           4 non-null      object
 5   boolean_rank  4 non-null      bool  
 6   etc           4 non-null      int64 
dtypes: bool(1), int64(2), object(4)
memory usage: 400.0+ bytes


In [143]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [144]:
df.nunique()

country         4
rank            4
grade           4
president       4
gdp             3
boolean_rank    2
etc             1
dtype: int64

## 데이터 정렬 (sort)

In [147]:
df.sort_values(by=['rank'])

country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
2      China     3     C   jinping  3000         False    0
7  singapore     5     E      jiao  2000         False    0

In [148]:
df.sort_values(by=['rank'], ascending=False) # ascending = False => 내림차순

country  rank grade president   gdp  boolean_rank  etc
7  singapore     5     E      jiao  2000         False    0
2      China     3     C   jinping  3000         False    0
1        usa     2     B     biden  2000          True    0
0        kor     1     A      yoon  1000          True    0

In [149]:
df.sort_values(by=['country'])

country  rank grade president   gdp  boolean_rank  etc
2      China     3     C   jinping  3000         False    0
0        kor     1     A      yoon  1000          True    0
7  singapore     5     E      jiao  2000         False    0
1        usa     2     B     biden  2000          True    0

In [150]:
df.sort_values(by=['gdp'])

country  rank grade president   gdp  boolean_rank  etc
0        kor     1     A      yoon  1000          True    0
1        usa     2     B     biden  2000          True    0
7  singapore     5     E      jiao  2000         False    0
2      China     3     C   jinping  3000         False    0

## null 데이터 처리
- NaN -> Not a Number (=> 비어있는 데이터, null, none 데이터)
- isnull() : 데이터가 null이니? -> boolean indexing
- fillna() : null 데이터들을 내가 원하는 어떤 값으로 채워주세요.
- dropna() : null 데이터를 제거해주세요.

In [151]:
df.isna()

country   rank  grade  president    gdp  boolean_rank    etc
0    False  False  False      False  False         False  False
1    False  False  False      False  False         False  False
2    False  False  False      False  False         False  False
7    False  False  False      False  False         False  False

In [153]:
df['check'] = np.nan
print(df)

     country  rank grade president   gdp  boolean_rank  etc  check
0        kor     1     A      yoon  1000          True    0    NaN
1        usa     2     B     biden  2000          True    0    NaN
2      China     3     C   jinping  3000         False    0    NaN
7  singapore     5     E      jiao  2000         False    0    NaN


In [154]:
df.isna()

country   rank  grade  president    gdp  boolean_rank    etc  check
0    False  False  False      False  False         False  False   True
1    False  False  False      False  False         False  False   True
2    False  False  False      False  False         False  False   True
7    False  False  False      False  False         False  False   True

In [ ]:
# null데이터를 마주했을 때?
# (1) 제거한다. => 제거하고자 하는 데이터가 소량일때
## 100만건의 데이터를 받음. nan데이터가 10만건 -> 지우고 90만건으로 분석을 했어요.
### 담당자가 -> 데이터는 100만건 드렸는데요? 왜 90만건에 대한 결과 밖에 업죠?
#### 제거를 하게되면 제거를 하게된 합당한 이유를 찾으셔야 합니다. 그리고 소통하셔야죠 (명분)

# (2) 값을 채워넣는다.
## 평균값을 넣는다. (통신사 고객 데이터 중 나이데이터가 비어있다 -> 고객 평균 나이를 넣어서 분석한다.)
## 계산을 해서 넣는다. (고객 비율 또는 고객 데이터 중에서 페북 메신저 앱이 설치가 되어있으면 10대일 가능성이 높다 -> 10대 평균값 넣는다)

# (3) 분석에서 제외한다.

# null 값이 안들어가게 하는 방법은 없나요?

# DE : 우리가 분석하는 데이터가 로그 데이터
# 기본적인 유저 데이터나 DB데이터들 -> BI로 보통 해결이 됨
# DS : 시각화 툴 사용 (엑셀 잘하면 엑셀, 다만 gpt가 더 잘한다)

# 코드를 다 이해해서 커스텀을 할 수 있어야 하니까

In [162]:
df.fillna(value="pass", inplace=True) # null 데이터를 채우고 싶을 때
print(df)

     country  rank grade president   gdp  boolean_rank  etc check
0        kor     1     A      yoon  1000          True    0  pass
1        usa     2     B     biden  2000          True    0  pass
2      China     3     C   jinping  3000         False    0  pass
7  singapore     5     E      jiao  2000         False    0  pass


In [170]:
df.iloc[2,3] = np.nan # 있는 데이터를 null 데이터로 바꿀 때
print(df)
print()
df.dropna(how="any") # null 데이터를 제거할때 ("any"는 그 행에 null이 하나라도 있으면 제거)
print(df)
print()
nullcheck_df = df.dropna(how="any")
print(nullcheck_df)

     country  rank grade president   gdp  boolean_rank  etc check
0        kor     1     A      yoon  1000          True    0  pass
1        usa     2     B     biden  2000          True    0  pass
2      China     3     C       NaN  3000         False    0  pass
7  singapore     5     E      jiao  2000         False    0  pass

     country  rank grade president   gdp  boolean_rank  etc check
0        kor     1     A      yoon  1000          True    0  pass
1        usa     2     B     biden  2000          True    0  pass
2      China     3     C       NaN  3000         False    0  pass
7  singapore     5     E      jiao  2000         False    0  pass

     country  rank grade president   gdp  boolean_rank  etc check
0        kor     1     A      yoon  1000          True    0  pass
1        usa     2     B     biden  2000          True    0  pass
7  singapore     5     E      jiao  2000         False    0  pass


In [171]:
df['birth'] = ["2020.12.03", "2021.03.13", "1998.07.13", "1955.08.13"]
print(df)

     country  rank grade president   gdp  boolean_rank  etc check       birth
0        kor     1     A      yoon  1000          True    0  pass  2020.12.03
1        usa     2     B     biden  2000          True    0  pass  2021.03.13
2      China     3     C       NaN  3000         False    0  pass  1998.07.13
7  singapore     5     E      jiao  2000         False    0  pass  1955.08.13


In [172]:
df["birth"].dtypes

dtype('O')

In [173]:
df.sort_values('birth')

country  rank grade president   gdp  boolean_rank  etc check       birth
7  singapore     5     E      jiao  2000         False    0  pass  1955.08.13
2      China     3     C       NaN  3000         False    0  pass  1998.07.13
0        kor     1     A      yoon  1000          True    0  pass  2020.12.03
1        usa     2     B     biden  2000          True    0  pass  2021.03.13

## merge(), concat()
- 서로다른 N개의 데이터 프레임을 합치기 위해 사용하는 함수
- 왜 합쳐주는 거죠? -. 데이터를 저장할때 (일자별로 csv파일이 하나씩 생성되는 구조라고 해봅시다. -> 한달이면 요일별로 해서 파일로 총 30개가 생성되겠죠.
-> 분석하려면 30개의 파일을 합쳐서 분석을 진행해야겠죠.

In [189]:
data = {
"고객번호" : [1001,1002,1003,1004],
"기업명" : ["LG", "Samsung", "Hyundai", "Kia"],
"시총" : ["10조", "44조", "22조", "3조"]
}
print(data)

{'고객번호': [1001, 1002, 1003, 1004], '기업명': ['LG', 'Samsung', 'Hyundai', 'Kia'], '시총': ['10조', '44조', '22조', '3조']}


In [190]:
df1 = pd. DataFrame(data)
print(df1)

   고객번호      기업명   시총
0  1001       LG  10조
1  1002  Samsung  44조
2  1003  Hyundai  22조
3  1004      Kia   3조


In [194]:
data = {
"고객번호" : [1001,1002,1005,1006],
"시총" : ["10조", "44조", "22조", "3조"]
}
df2 = pd.DataFrame(data)
print(df2)

   고객번호   시총
0  1001  10조
1  1002  44조
2  1005  22조
3  1006   3조


In [192]:
pd.merge(df1, df2, how = "outer")


고객번호      기업명   시총
0  1001       LG  10조
1  1002  Samsung  44조
2  1003  Hyundai  22조
3  1004      Kia   3조
4  1005      NaN  22조
5  1006      NaN   3조

In [193]:
pd.merge(df2, df1, how = "outer")

고객번호   시총      기업명
0  1001  10조       LG
1  1002  44조  Samsung
2  1005  22조      NaN
3  1006   3조      NaN
4  1003  22조  Hyundai
5  1004   3조      Kia

In [195]:
pd.merge(df1, df2, how="right")

고객번호      기업명   시총
0  1001       LG  10조
1  1002  Samsung  44조
2  1005      NaN  22조
3  1006      NaN   3조

In [196]:
pd.merge(df1, df2, how="left")

고객번호      기업명   시총
0  1001       LG  10조
1  1002  Samsung  44조
2  1003  Hyundai  22조
3  1004      Kia   3조

In [199]:
pd.merge(df1, df2, how="outer")
df.to_csv("pandas result.csv", encoding="utf-8-sig") # 최종 결과 csv 저장
pd.read_csv("pandas result.csv") # 최종 결과 csv 파일 read

Unnamed: 0    country  rank grade president   gdp  boolean_rank  etc check  \
0           0        kor     1     A      yoon  1000          True    0  pass   
1           1        usa     2     B     biden  2000          True    0  pass   
2           2      China     3     C       NaN  3000         False    0  pass   
3           7  singapore     5     E      jiao  2000         False    0  pass   

        birth  
0  2020.12.03  
1  2021.03.13  
2  1998.07.13  
3  1955.08.13

In [206]:
# concat
df_1 = pd.DataFrame({"A": [1,2], "B" : [3,4]})
df_2 = pd.DataFrame({"A": [5,6], "B" : [7,8]})
print(df_1)
print("======")
print(df_2)

   A  B
0  1  3
1  2  4
   A  B
0  5  7
1  6  8


In [207]:
# (1) 세로로 합친다
result = pd.concat([df_1,df_2], axis=0, ignore_index = True)
print(result)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8


In [208]:
# (2) 가로로 합친다

result2 = pd.concat([df_1,df_2], axis = 1, ignore_index = True)
print(result2)

   0  1  2  3
0  1  3  5  7
1  2  4  6  8


In [212]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df

영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [ ]:
# 1) 전체 데이터 중에서 "영화" 정보만 출력하시오.
# 2) 전체 데이터 중에서 "영화", "평점" 정보를 출력하시오
# 3) 2015년 이후에 개봉한 영화 데이터 중에서 "영화", "개봉연도" 정보를 출력하시오.
# 4) 주어진 계산식을 참고하여 "추천 점수" column을 추가하시오.
# * 추천점수 = (관객수 * 평점) // 100
# 5) 전체 데이터를 "개봉연도" 기준 내림차순으로 출력하시오

In [259]:
# 1) 전체 데이터 중에서 "영화" 정보만 출력하시오.
df["영화"]

0           명량
1         극한직업
2    신과함께-죄와 벌
3         국제시장
4           괴물
5          도둑들
6      7번방의 선물
7           암살
Name: 영화, dtype: object

In [258]:
df.영화

0           명량
1         극한직업
2    신과함께-죄와 벌
3         국제시장
4           괴물
5          도둑들
6      7번방의 선물
7           암살
Name: 영화, dtype: object

In [261]:
df.loc[:,"영화"]

0           명량
1         극한직업
2    신과함께-죄와 벌
3         국제시장
4           괴물
5          도둑들
6      7번방의 선물
7           암살
Name: 영화, dtype: object

In [224]:
# 2) 전체 데이터 중에서 "영화", "평점" 정보를 출력하시오
df[['영화', "평점"]]

영화    평점
0         명량  8.88
1       극한직업  9.20
2  신과함께-죄와 벌  8.73
3       국제시장  9.16
4         괴물  8.62
5        도둑들  7.64
6    7번방의 선물  8.83
7         암살  9.10

In [272]:
# 3) 2015년 이후에 개봉한 영화 데이터 중에서 "영화", "개봉연도" 정보를 출력하시오.
df.loc[df["개봉 연도"]>=2015, ["영화", "개봉 연도"]]
df[df["개봉 연도"]> 2015] [["영화", "개봉 연도"]]

영화  개봉 연도
1       극한직업   2019
2  신과함께-죄와 벌   2017

In [256]:
df["추천점수"] = (df["관객 수"] * df["평점"])//100
df

영화  개봉 연도  관객 수    평점   추천점수
0         명량   2014  1761  8.88  156.0
1       극한직업   2019  1626  9.20  149.0
2  신과함께-죄와 벌   2017  1441  8.73  125.0
3       국제시장   2014  1426  9.16  130.0
4         괴물   2006  1301  8.62  112.0
5        도둑들   2012  1298  7.64   99.0
6    7번방의 선물   2013  1281  8.83  113.0
7         암살   2015  1270  9.10  115.0

In [257]:
df.sort_values(by=["개봉 연도"], ascending = False)

영화  개봉 연도  관객 수    평점   추천점수
1       극한직업   2019  1626  9.20  149.0
2  신과함께-죄와 벌   2017  1441  8.73  125.0
7         암살   2015  1270  9.10  115.0
0         명량   2014  1761  8.88  156.0
3       국제시장   2014  1426  9.16  130.0
6    7번방의 선물   2013  1281  8.83  113.0
5        도둑들   2012  1298  7.64   99.0
4         괴물   2006  1301  8.62  112.0