In [2]:
import numpy as np

Q1. 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요.

In [4]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr_avg = np.average(arr, axis = 1)
print(arr_avg)

[2. 5. 8.]


Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요.

In [30]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr_evens = np.arange(2, arr.size,2)
print(arr_evens)


[2 4 6 8]


Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요.

In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_diag = np.diag(arr)
print(arr_diag)
print(arr.diagonal(0))

[1 5 9]
[1 5 9]


Q4. 2차원 배열에서 각 열의 표준 편차를 계산하는 코드를 작성하세요.

In [38]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr_stdev_0 = np.std(arr, axis = 0) # y축에서 가로로 뻗어가는
arr_stdev_1 = np.std(arr, axis = 1) # x축에서 세로로 뻗어가는
print(arr_stdev_0)
print(arr_stdev_1)

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


Q5. 1차원 배열에서 원소들의 순위를 계산하는 코드를 작성하세요.

In [113]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
arr_sorted = np.sort(arr)
print(arr_sorted[::-1])

[9 6 5 4 3 2 1 1]


Q6. 2차원 배열에서 각 행의 최대값과 그 인덱스를 출력하는 코드를 작성하세요.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_max = np.max(arr, axis = 1)

np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_max)

arr_max_0 = np.where(arr == arr_max[0])
arr_max_1 = np.where(arr == arr_max[1])
arr_max_2 = np.where(arr == arr_max[2])
arr_max_3 = np.amax(arr, axis = 0)
arr_max_4 = np.max(arr,axis = 0)

print(arr_max_0)
print(arr_max_1)
print(arr_max_2)
print(arr_max_3)
print(arr_max_4)

[3 6 9]
(array([0]), array([2]))
(array([1]), array([2]))
(array([2]), array([2]))
[7 8 9]
[7 8 9]


Q7. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.

In [90]:
arr = np.array([1, 2, 3, 4, 5])
arr_med = np.median(arr)
print(int(arr_med))

3


Q8. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.

In [100]:
arr = np.array([1, 4, 6, 3, 9, 2, 7, 8])
print(arr[arr >= 5])

[6 9 7 8]


Q9. 2차원 배열에서 모든 원소의 값을 2배로 만드는 코드를 작성하세요.

In [101]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_doub = arr*2
print(arr_doub)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Q10. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.

In [111]:
arr = np.array([1, 3, 5, 2, 4, 6, 3, 5, 7])
ind_3 = np.where(arr == 3)
ind_5 = np.where(arr == 5)

ind_3_5 = np.append(ind_3, ind_5)
print(np.sort(ind_3_5))

[1 2 6 7]


Q11. 2차원 배열에서 행렬의 각 열의 값을 오름차순으로 정렬하는 코드를 작성하세요.

In [112]:
arr = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]]) # 3x3, 2차원 행렬

arr_sorted_1 = np.sort(arr)
print(arr_sorted_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q12. 1차원 배열에서 중복되는 값을 제거하는 코드를 작성하세요.

In [115]:
arr = np.array([1, 2, 3, 2, 4, 3, 5])

arr_unique = np.unique(arr)

print(arr_unique)

[1 2 3 4 5]
