In [3]:
!pip install numpy pandas matplotlib seaborn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 26.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 29.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.7/229.7 kB 27.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 19.2 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 9.9 MB/s eta 0:00:00


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

- dataframe은 2차원 테이블이고, 테이블의 한 줄(행/열)을 series라고 합니다.
- series의 모임이 곧, datafram이 됩니다.

In [6]:
# s는 1, 3, 5, 6, 8을 원소로 가지는 pandas.Series
pd.Series([1, 3, 5, 6, 8])

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [16]:
# 12 x 4 행렬에 1부터 48까지의 숫자를 원소를 가지고, index는 0부터 시작하고, column은 순서대로 X1, X2, X3, X4로 하는 data frame 생성
df = pd.DataFrame(data=np.arange(1,49).reshape(12,4),
                 columns= ["X1", "X2", "X3", "X4"])
print(df)

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48


In [17]:
# dataframe index
print(df.index)

RangeIndex(start=0, stop=12, step=1)


In [20]:
#dataframe columns
print(df.columns)

Index(['X1', 'X2', 'X3', 'X4'], dtype='object')


In [24]:
#dataframe values
print(df.values)
df.values

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [26]:
# 특정 column을 가져오기
df["X1"]

0      1
1      5
2      9
3     13
4     17
5     21
6     25
7     29
8     33
9     37
10    41
11    45
Name: X1, dtype: int64

In [28]:
# X1 column에 2 더하기
df["X1"]+2

0      3
1      7
2     11
3     15
4     19
5     23
6     27
7     31
8     35
9     39
10    43
11    47
Name: X1, dtype: int64

In [32]:
# dataframe의 맨 위 다섯줄을 보여주는 head()
print(df.head())

   X1  X2  X3  X4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [34]:
# 10줄
print(df.head(10))

   X1  X2  X3  X4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24
6  25  26  27  28
7  29  30  31  32
8  33  34  35  36
9  37  38  39  40


In [38]:
# dataframe에 대한 전체적인 요약정보를 보여줍니다. index, columns, null/notnullcount
print(df.info)
print()
print(df.info())

<bound method DataFrame.info of     X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      12 non-null     int64
 1   X2      12 non-null     int64
 2   X3      12 non-null     int64
 3   X4      12 non-null     int64
dtypes: int64(4)
memory usage: 512.0 bytes
None


In [39]:
# dataframe에 대한 전체적인 통계정보를 보여줍니다.
df.describe()

X1         X2         X3         X4
count  12.000000  12.000000  12.000000  12.000000
mean   23.000000  24.000000  25.000000  26.000000
std    14.422205  14.422205  14.422205  14.422205
min     1.000000   2.000000   3.000000   4.000000
25%    12.000000  13.000000  14.000000  15.000000
50%    23.000000  24.000000  25.000000  26.000000
75%    34.000000  35.000000  36.000000  37.000000
max    45.000000  46.000000  47.000000  48.000000

In [42]:
# X2 column을 기준으로 내림차순 정렬
print(df.sort_values(by="X2", ascending=False))
print()
print(df.sort_values(by="X2"))

    X1  X2  X3  X4
11  45  46  47  48
10  41  42  43  44
9   37  38  39  40
8   33  34  35  36
7   29  30  31  32
6   25  26  27  28
5   21  22  23  24
4   17  18  19  20
3   13  14  15  16
2    9  10  11  12
1    5   6   7   8
0    1   2   3   4

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48


### Fancy Indexing

In [44]:
# dataframe에서 slicing을 이용하면 row 단위로 잘려나옵니다.
# 앞에서 3줄을 slicing 합니다.
print(df[0:3])

   X1  X2  X3  X4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12


In [45]:
# dataframe에서 index value를 기준으로 indexing도 가능합니다. (여전히 row 단위)
# 두번째 row
print(df.loc[0])
print(df.loc[2])

X1    1
X2    2
X3    3
X4    4
Name: 0, dtype: int64
X1     9
X2    10
X3    11
X4    12
Name: 2, dtype: int64


In [52]:
# df.loc는 특정값을 기준으로 indexing합니다. (key - value)
print(df.loc[0]["X2"])
print(df.loc[0][2])
print(df.loc[0]["X3"])

2
3
3


In [56]:
# df.loc에 2차원 indexing도 가능합니다.
# df.loc["row에 대한 조건", "col에 대한 조건"]
print(df.loc[4, "X2"])
print()
print(df.loc[[0, 3], ["X1", "X3"]])
print()
print(df.loc[0:4, "X1":"X3"]) # loc로 slicing하면 모든 범위가 포함된다! => 리스트의 slicing과는 다름

18

   X1  X3
0   1   3
3  13  15

   X1  X2  X3
0   1   2   3
1   5   6   7
2   9  10  11
3  13  14  15
4  17  18  19


In [78]:
## boolean mask == filter

mask = df["X1"] > 10 # row에 대한 조건
print(mask)
print()
print(df.loc[mask])

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
Name: X1, dtype: bool

    X1  X2  X3  X4
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48


In [79]:
# Q1. df에서 X2 column이 20 이상인 모든 데이터 (row)를 출력하세요.
# print(df.loc[[0, 3], ["X1", "X3"]])
mask_2 = df["X2"] >= 20
print(df.loc[mask_2])
print()
print(df.loc[df["X2"] >= 20])

    X1  X2  X3  X4
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

    X1  X2  X3  X4
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48


In [80]:
# Q2. df에서 X2 column이 20 이상인 X4를 출력하세요.
mask_3 = df["X2"] >= 20
print(df.loc[mask_3]["X4"])

5     24
6     28
7     32
8     36
9     40
10    44
11    48
Name: X4, dtype: int64


In [86]:
# Q3. X3 column에서 10이상 30 이하인 데이터를 뽑아주세요.
mask_4 = 10 <= df["X3"]
mask_5 = df["X3"] <= 30
print(df.loc[mask_4])
print()
print(df.loc[mask_5])

    X1  X2  X3  X4
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

   X1  X2  X3  X4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24
6  25  26  27  28


In [90]:
mask_4 = 10 <= df["X3"]
mask_5 = df["X3"] <= 30
mask_6 = (10 <= df["X3"]) & (df["X3"] <= 30)
print(df.loc[mask_6])
print()
print(df.loc[mask_4 & mask_5])

   X1  X2  X3  X4
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24
6  25  26  27  28

   X1  X2  X3  X4
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24
6  25  26  27  28


In [100]:
# Q4. X3 column에서 10이하 30이상인 데이터를 뽑아주세요.
mask_7 = df["X3"] <= 10
mask_8 = 30 <= df["X3"]
mask_9 = (30 <= df["X3"]) | (df["X3"] <= 10)
print(df.loc[mask_9])
print()
print(df.loc[(30 <= df["X3"]) | (df["X3"] <= 10)])

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48


In [109]:
# iloc로 2차원 indexing을 하게되면, row 기준으로 index 3,4를 가져오고 column 기준으로 0, 1을 가져옵니다.
# Q1. 3번째 row부터 8번째 row까지, 첫번째 column부터 3개

print(df.iloc[2:8, 0:3])

   X1  X2  X3
2   9  10  11
3  13  14  15
4  17  18  19
5  21  22  23
6  25  26  27
7  29  30  31


## 04. 엑셀의 피벗테이블 판다스에도 있다

- pivot table이란 기존 테이블 구조를 특정 column을 기준으로 재구조화한 테이블을 말합니다.

- 특정 column을 기준으로 pivot하기 때문에, 어떤 column에 어떤 연산을 하느냐에 따라서 만들어지는 결과가 바뀝니다.

- 주로 어떤 column을 기준으로 데이터를 해석하고 싶을 때 사용합니다.

In [111]:
# 타이타닉 데이터 불러오기
titanic = pd.read_csv("./data/titanic.csv")
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [114]:
# 데이터 크기, 데이터 Column 정보, Null count(결측치 개수), column별 데이터 타입
print(titanic.info())

print()
# 통계량
print(titanic.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.4865

In [118]:
# Age가 30세 이상인 사람들의 이름
print(titanic.loc[titanic["Age"] >= 30, "Name"])

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
6                                McCarthy, Mr. Timothy J
11                              Bonnell, Miss. Elizabeth
                             ...                        
873                          Vander Cruyssen, Mr. Victor
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
881                                   Markun, Mr. Johann
885                 Rice, Mrs. William (Margaret Norton)
890                                  Dooley, Mr. Patrick
Name: Name, Length: 330, dtype: object


In [129]:
# 성별을 기준으로 생존률 파악 --> Mean vs Sum
print(pd.pivot_table(data=titanic,
               index="Sex",
               values="Survived")) # 아무것도 안쓰면 Mean, 평균
print()
print(pd.pivot_table(data=titanic,
               index="Sex",
               values="Survived",
                    aggfunc=["mean","sum","count"])) # 아무것도 안쓰면 Mean, 평균


        Survived
Sex             
female  0.742038
male    0.188908

            mean      sum    count
        Survived Survived Survived
Sex                               
female  0.742038      233      314
male    0.188908      109      577


In [137]:
# 사회 계급을 기준으로 생존률 파악
print(pd.pivot_table(data=titanic,
               index=["Pclass","Sex"],
                 values="Survived",
               aggfunc=["count", "sum","mean"]))

                 count      sum      mean
              Survived Survived  Survived
Pclass Sex                               
1      female       94       91  0.968085
       male        122       45  0.368852
2      female       76       70  0.921053
       male        108       17  0.157407
3      female      144       72  0.500000
       male        347       47  0.135447
